[global]
repo1-type=s3
repo1-path=/zoen
repo1-s3-endpoint=fly.storage.tigris.dev
repo1-s3-region=auto
repo1-s3-uri-style=path
repo1-retention-full=3
repo1-retention-diff=14
repo1-cipher-type=aes-256-cbc
repo1-bundle=y
repo1-block=y
compress-type=zst
process-max=1
start-fast=y
log-level-console=warn
log-level-file=off
lock-path=/tmp/pgbackrest
archive-timeout=120
io-timeout=60

[global:restore]
process-max=8

[zoen]
pg1-path=/data/pgdata
pg1-port=5432
pg1-socket-path=/var/run/postgresql
pg1-user=postgres
